### ISSUE TITLE
Added additional requirements

### ISSUE THREAD

**Issue by renestadler** [htl-perg-2019-20-5bhif/anagram-checker-exercise-renestadler#1]
Dear Mr. Stropek!

I've completed the Anagram-Checker exercise including both additional requirements.

Yours,
René

**Comment by rstropek** [comment]
Thank you, looks good. Here some tips for further improvement:

* Avoid properties starting with lowercase letters (e.g. `WordPair.word1`). This is not [ideomatic](https://stackoverflow.com/a/84270/3548127) C#.
* If a property (e.g. `WordPair.word1`) is never changed after assignment in ctor, there [should be no setter](https://stackoverflow.com/a/2719806/3548127).
* Avoid static functions that perform core business logic (e.g. `AnagramChecker.CheckWords`) because they are harder to test. It is possible, but when in doubt, prefer instance members over static ones.
* Methods returning `Task<T>` should have the postfix `Async` in their name (e.g. `DoSomethingAsync`).
* `return await Task.Run(() => GeneratePermutations(wordToPermute, 0));` does not make sense. If you want to turn a non-Task- into a Task-result, use [`Task.FromResult`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.fromresult?view=netcore-3.0) instead.
* `ListAnagramsFromDictionary` does not follow the *single resposibility* principle. It contains I/O (reading fil) and business logic.
* @`SwapChars`: Did you know that you change exchange variables without helper var? [Description](https://stackoverflow.com/a/39190792/3548127)

In general, well done. The two extra points are yours.

Greetings,
Rainer Stropek.
